# Generated by Django 5.2.1 on 2025-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Course_Name', models.CharField(max_length=100)),
                ('Student_Id', models.IntegerField(max_length=20)),
                ('Email_address', models.EmailField(max_length=100, unique=True)),
                ('Contact_No', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
