# Generated by Django 5.2.1 on 2025-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Id',
            field=models.IntegerField(),
        ),
    ]
